# See https://docs.docker.com/compose/compose-file/ for information about what
# commands you can use in this file.
#
# Note that you must use the `docker stack deploy` command, with any required
# command line flags, in order to actually get any replicas started. That
# command requires that a docker swarm is already running in order to function.

version: "3"
services:
  root_node:
    image: kadlab
    networks:
      kademlia_network:
        ipv4_address: 172.16.238.10
    ports:
      - 8080:8080
 
  kademlia_nodes:
    image: kadlab # Make sure your Docker image has this name.
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - kademlia_network

      
networks:
  kademlia_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24  # Manually configure the subnet for static IPs